import * as tf from "@tensorflow/tfjs-node";
import { MiniBitNetStrategy } from "../lib/strategy/MiniBitNetStrategy";
import { PersistentState } from "../lib/PersistentState";
import { expect } from "chai";
import * as sinon from "sinon";

describe.skip("MiniBitNetStrategy", function () {
  it("prepareInitialWeights", function () {
    const strategy = new MiniBitNetStrategy();
    const targetShape: [number, number] = [4, 4];
    const floatInitializer = tf.initializers.glorotUniform({});
    const baseFloatWeights = floatInitializer.apply(targetShape, "float32");
    const state = new PersistentState();

    const packed = strategy.prepareInitialWeights(baseFloatWeights, state);
    const { weight, momentum } = strategy.unpack(packed);
    const resolved = tf.add(weight, momentum);
    console.log(packed.dataSync());
    console.log(weight.dataSync());
    console.log(momentum.dataSync());
    console.log(baseFloatWeights.dataSync());
    console.log(resolved.dataSync());
  });

  it("decodeWeights", function () {});

  it("pack/unpack", function () {
    const strategy = new MiniBitNetStrategy();
    const ternaries = tf.tensor2d([-1.0, 0.0, 1.0, 0.0], [4, 1]);
    const residuals = tf.tensor2d([-0.42, -0.99, -0.003, 20.672], [4, 1]);
    const packed = strategy.pack(ternaries, residuals);
    const { weight, momentum } = strategy.unpack(packed);
    console.log(packed.dataSync());
    console.log(weight.dataSync());
    console.log(momentum.dataSync());
  });

  describe.only("applyStochasticRounding", () => {
    /**
     * Helper function to extract the exact threshold generated by tf.randomUniform
     * on your local machine for a specific seed.
     */
    function getThresholdForSeed(seed: number, shape: number[]): number {
      return tf.tidy(() => {
        const thresholds = tf.randomUniform(shape, 0, 1, "float32", seed);
        return thresholds.dataSync()[0]; // Extract the precise scalar threshold value
      });
    }

    it("Scenario 1: Flip passes (Residual magnitude > random threshold)", async () => {
      const targetSeed = 1;
      const shape = [1];

      // 1. Check what threshold your specific machine naturally outputs for Seed 1
      const localThreshold = getThresholdForSeed(targetSeed, shape);

      // 2. Proactively set our residual to be strictly GREATER than your system's threshold
      const residualValue = Math.min(localThreshold + 0.1, 0.95);

      const strategy = new MiniBitNetStrategy(targetSeed);
      const ternary = tf.tensor1d([-1]);
      const residual = tf.tensor1d([residualValue]);

      const result = strategy.applyStochasticRounding(ternary, residual);

      // Expected: Magnitude was larger than threshold, so flip is GUARANTEED to pass.
      // Ternary safely increments from -1 -> 0.
      tf.test_util.expectArraysClose(await result.ternary.data(), [0]);
      tf.test_util.expectArraysClose(await result.residual.data(), [residualValue - 1.0]);

      tf.dispose([ternary, residual, result.ternary, result.residual]);
    });

    it("Scenario 2: Flip fails (Residual magnitude < random threshold)", async () => {
      const targetSeed = 1;
      const shape = [1];

      // 1. Get the local threshold
      const localThreshold = getThresholdForSeed(targetSeed, shape);

      // 2. Proactively set our residual to be strictly LESS than your system's threshold
      const residualValue = Math.max(localThreshold - 0.1, 0.05);

      const strategy = new MiniBitNetStrategy(targetSeed);
      const ternary = tf.tensor1d([-1]);
      const residual = tf.tensor1d([residualValue]);

      const result = strategy.applyStochasticRounding(ternary, residual);

      // Expected: Magnitude was lower than threshold, so flip is GUARANTEED to fail.
      // Ternary stays stuck at -1.
      tf.test_util.expectArraysClose(await result.ternary.data(), [-1]);
      tf.test_util.expectArraysClose(await result.residual.data(), [residualValue]);

      tf.dispose([ternary, residual, result.ternary, result.residual]);
    });

    it("Scenario 3: Boundary clamping with large values overrides stochastic path", async () => {
      // Clamping works regardless of whether the stochastic flip triggers or skips.
      const strategy = new MiniBitNetStrategy(1);

      const ternary = tf.tensor1d([0]);
      const residual = tf.tensor1d([2.5]); // Int portion = 2, frac portion = 0.5

      const result = strategy.applyStochasticRounding(ternary, residual);

      const ternaryData = await result.ternary.data();
      const residualData = await result.residual.data();

      // The boundary check forces clamping to 1 regardless of the underlying random uniform value
      expect(ternaryData[0]).to.equal(1);
      expect(residualData[0]).to.be.closeTo(1.5, 0.0001);

      tf.dispose([ternary, residual, result.ternary, result.residual]);
    });

    it("Memory Leak Protection: Verifying zero unmanaged tensor footprint", () => {
      const initialTensors = tf.memory().numTensors;
      const strategy = new MiniBitNetStrategy(42);

      const ternary = tf.tensor1d([0]);
      const residual = tf.tensor1d([0.5]);

      const result = strategy.applyStochasticRounding(ternary, residual);

      result.ternary.dispose();
      result.residual.dispose();
      ternary.dispose();
      residual.dispose();

      expect(tf.memory().numTensors).to.equal(initialTensors);
    });
  });
});
